AWSTemplateFormatVersion: "2010-09-09"

Description: >- 
  VPC Traffic Mirroring NLB template. Template is launched if traffic mirror
  target type is set to NLB. Template creates NLB to use as Traffic Mirroring
  target. Template can also be launched standalone (qs-1s0om7h6j).

Metadata:
  QSLint:
    Exclusions: [W9901]
  LintSpellExclude:
    - Linux
    - Amazon
    - VPC
    - Traffic Mirroring
    - Network Load Balancer
    - CIDR
    - DMZ
    - GB
    - Region
    - S3
    - AmazonS3
    - QSS3BucketName
    - Quick Start
    - SSH
    - customizing
    - ID
    - VPCID
    - vpc
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Network Load Balancer Configuration'
        Parameters:
          - NLBScheme
          - NLBSubnet1ID
          - NLBSubnet2ID
      - Label:
          default: 'Target group configuration'
        Parameters:
          - VPCID
    ParameterLabels:
      VPCID:
        default: VPC ID
      NLBScheme:
        default: Network Load Balancer Scheme
      NLBSubnet1ID:
        default: ID of Subnet 1 to be associated with NLB
      NLBSubnet2ID:
        default: ID of Subnet 2 to be associated with NLB

Parameters:
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e).
    Type: 'AWS::EC2::VPC::Id'
  NLBScheme:
    Description: >-
      Network Load Balancer scheme. Valid values are internet-facing and 
      internal. The default is internal.
    Default: internal
    AllowedValues: ['internet-facing', 'internal']
    Type: String
    ConstraintDescription: 'Must be a valid ELB scheme'
  NLBSubnet1ID:
    Description: ID of Subnet 1 to be associated with NLB (e.g., subnet-11223344, subnet-55667788).
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be a valid subnet ID
  NLBSubnet2ID:
    Description: ID of Subnet 2 to be associated with NLB (e.g., subnet-11223344, subnet-55667788).
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be a valid subnet ID

Resources:
  Nlb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: !Ref NLBScheme
      Type: network
      Subnets: 
        - !Ref NLBSubnet1ID
        - !Ref NLBSubnet2ID
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-nlb-1"

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 4789
      Protocol: UDP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      VpcId: !Ref VPCID
      HealthCheckPort: '80'
      HealthCheckProtocol: HTTP 
      Tags:
      - Key: Name
        Value: !Sub "${AWS::StackName}-nlb1-tg1"

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 4789
      Protocol: UDP
      DefaultActions:
      - Type: forward
        TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref Nlb

Outputs:
  NetworkLoadBalancerARN:
    Description: Network Load Balancer ARN
    Value: !Ref Nlb
  TargeGroupARN:
    Description: Target Group ARN
    Value: !Ref TargetGroup